export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const LOCALE_SET = "LOCALE_SET";

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";
export const FETCH_CURRENT_USER_REQUEST = "FETCH_CURRENT_USER_REQUEST";
export const FETCH_CURRENT_USER_SUCCESS = "FETCH_CURRENT_USER_SUCCESS";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const CONFIRM_USER_REQUEST = "CONFIRM_USER_REQUEST";
export const CONFIRM_USER_FAILURE = "CONFIRM_USER_FAILURE";

export const FETCH_ALL_USERS_REQUEST = "FETCH_ALL_USERS_REQUEST";
export const FETCH_ALL_USERS_SUCCESS = "FETCH_ALL_USERS_SUCCESS";
export const FETCH_ALL_USERS_FAILURE = "FETCH_ALL_USERS_FAILURE";

export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";

export const FETCH_CUSTOMERS_REQUEST = "FETCH_CUSTOMERS_REQUEST";
export const FETCH_CUSTOMERS_SUCCESS = "FETCH_CUSTOMERS_SUCCESS";
export const FETCH_CUSTOMERS_FAILURE = "FETCH_CUSTOMERS_FAILURE";

export const ADD_CUSTOMER_REQUEST = "ADD_CUSTOMER_REQUEST";
export const ADD_CUSTOMER_FAILURE = "ADD_CUSTOMER_FAILURE";
export const ADD_CUSTOMER_SUCCESS = "ADD_CUSTOMER_SUCCESS";

export const FETCH_SINGLE_CUSTOMER_REQUEST = "FETCH_SINGLE_CUSTOMER_REQUEST";
export const FETCH_SINGLE_CUSTOMER_SUCCESS = "FETCH_SINGLE_CUSTOMER_SUCCESS";
export const FETCH_SINGLE_CUSTOMER_FAILURE = "FETCH_SINGLE_CUSTOMER_FAILURE";

export const UPDATE_SINGLE_CUSTOMER_REQUEST = "UPDATE_SINGLE_CUSTOMER_REQUEST";
export const UPDATE_SINGLE_CUSTOMER_SUCCESS = "UPDATE_SINGLE_CUSTOMER_SUCCESS";
export const UPDATE_SINGLE_CUSTOMER_FAILURE = "UPDATE_SINGLE_CUSTOMER_FAILURE";

export const DELETE_SINGLE_CUSTOMER_REQUEST = "DELETE_SINGLE_CUSTOMER_REQUEST";
export const DELETE_SINGLE_CUSTOMER_SUCCESS = "DELETE_SINGLE_CUSTOMER_SUCCESS";
export const DELETE_SINGLE_CUSTOMER_FAILURE = "DELETE_SINGLE_CUSTOMER_FAILURE";
